# Configuración para sistema multi-agente colaborativo
# IA Agent para Generación de Pruebas Unitarias .NET

# =============================================================================
# CONFIGURACIÓN DEL SISTEMA MULTI-AGENTE
# =============================================================================
multi_agent:
  mode: "collaborative"  # collaborative, competitive, hierarchical
  coordination_strategy: "group_chat"  # group_chat, agent_chat, workflow
  
  # Configuración de agentes
  agents:
    - name: "analysis_agent"
      role: "Analista"
      description: "Analiza código .NET y extrae información"
      enabled: true
      priority: 1
      
    - name: "generation_agent"
      role: "Generador"
      description: "Genera código de pruebas y templates"
      enabled: true
      priority: 2
      
    - name: "validation_agent"
      role: "Validador"
      description: "Valida código generado y ejecuta pruebas"
      enabled: true
      priority: 3
      
    - name: "optimization_agent"
      role: "Optimizador"
      description: "Optimiza pruebas y sugiere mejoras"
      enabled: true
      priority: 4
      
    - name: "coordinator_agent"
      role: "Coordinador"
      description: "Coordina tareas y gestiona flujo de trabajo"
      enabled: true
      priority: 0  # Mayor prioridad

# =============================================================================
# CONFIGURACIÓN DE COMUNICACIÓN
# =============================================================================
communication:
  # GroupChat (AutoGen)
  group_chat:
    enabled: true
    max_rounds: 10
    speaker_selection_method: "auto"  # auto, manual, round_robin
    allow_repeat_speaker: false
    
  # AgentChat (AutoGen)
  agent_chat:
    enabled: true
    max_turns: 5
    timeout: 60
    
  # Comunicación asíncrona
  async:
    enabled: true
    message_queue_size: 100
    processing_timeout: 30

# =============================================================================
# CONFIGURACIÓN DE MEMORIA COMPARTIDA
# =============================================================================
shared_memory:
  enabled: true
  storage_path: "./memory/shared"
  
  # Tipos de memoria compartida
  types:
    - "conversation_history"
    - "project_context"
    - "learned_patterns"
    - "user_preferences"
    
  # Configuración de sincronización
  sync:
    interval: 30  # segundos
    on_change: true
    conflict_resolution: "last_write_wins"  # last_write_wins, merge, manual

# =============================================================================
# CONFIGURACIÓN DE FLUJOS DE TRABAJO
# =============================================================================
workflows:
  # Flujo de generación completa
  complete_generation:
    enabled: true
    steps:
      - agent: "coordinator_agent"
        action: "analyze_request"
      - agent: "analysis_agent"
        action: "analyze_project"
      - agent: "generation_agent"
        action: "generate_tests"
      - agent: "validation_agent"
        action: "validate_code"
      - agent: "optimization_agent"
        action: "optimize_tests"
      - agent: "coordinator_agent"
        action: "consolidate_results"
        
  # Flujo de análisis y optimización
  analysis_optimization:
    enabled: true
    steps:
      - agent: "coordinator_agent"
        action: "coordinate_analysis"
      - agent: "analysis_agent"
        action: "analyze_existing_tests"
      - agent: "validation_agent"
        action: "run_tests_and_analyze"
      - agent: "optimization_agent"
        action: "identify_improvements"
      - agent: "generation_agent"
        action: "generate_additional_tests"
      - agent: "coordinator_agent"
        action: "present_optimization_report"

# =============================================================================
# CONFIGURACIÓN DE RESOLUCIÓN DE CONFLICTOS
# =============================================================================
conflict_resolution:
  strategy: "consensus"  # consensus, majority, coordinator_decides
  
  # Configuración de consenso
  consensus:
    required_agents: 3
    timeout: 60
    
  # Configuración de mayoría
  majority:
    threshold: 0.6
    
  # Configuración de decisión del coordinador
  coordinator:
    fallback_enabled: true
    override_threshold: 0.8

# =============================================================================
# CONFIGURACIÓN DE MONITOREO
# =============================================================================
monitoring:
  enabled: true
  
  # Métricas a monitorear
  metrics:
    - "agent_response_time"
    - "task_completion_rate"
    - "collaboration_efficiency"
    - "memory_usage"
    - "error_rate"
    
  # Configuración de alertas
  alerts:
    enabled: true
    thresholds:
      response_time: 30  # segundos
      error_rate: 0.1    # 10%
      memory_usage: 0.8  # 80%

# =============================================================================
# CONFIGURACIÓN DE PERFORMANCE
# =============================================================================
performance:
  # Configuración de concurrencia
  concurrency:
    max_parallel_agents: 3
    max_parallel_tasks: 5
    
  # Configuración de timeouts
  timeouts:
    agent_response: 30
    task_completion: 300
    workflow_completion: 600
    
  # Configuración de recursos
  resources:
    memory_limit_per_agent: "512MB"
    cpu_limit_per_agent: 1
    max_total_memory: "4GB"

# =============================================================================
# CONFIGURACIÓN DE APRENDIZAJE COLABORATIVO
# =============================================================================
collaborative_learning:
  enabled: true
  
  # Configuración de aprendizaje
  learning:
    pattern_detection: true
    knowledge_sharing: true
    experience_transfer: true
    
  # Configuración de actualización de conocimiento
  knowledge_update:
    interval: 3600  # segundos (1 hora)
    threshold: 0.7  # confianza mínima para actualizar
    validation_required: true
